// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/coffeenights/conure/apis/core/v1alpha1

// Package v1alpha1 contains API Schema definitions for the  v1alpha1 API group
// +kubebuilder:object:generate=true
// +groupName=core.conure.io
package v1alpha1
