// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
//	gitRepository: "https://github.com/coffeenights/conure.git"
//	branch: "main"
//	imagePullSecretsName: "regcred"
//	message: "Building Conure!"
	storageSize: "10Gi"
//	namespace: "conure-system"
}
