apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: conure-system
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.8
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
  namespace: conure-system
spec:
  selector:
    app: registry
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

