apiVersion: v1
kind: Namespace
metadata:
  name: conure-system
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
  namespace: conure-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: conure-system
spec:
  dnsNames:
    - "registry-service.conure-system.svc.cluster.local"
    - "registry-service.conure-system.svc"
    - "registry-service.conure-system"
    - "dev.conure.local"
  secretName: registry-tls
  issuerRef:
    name: self-signed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: conure-system
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.8
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: certificate-volume
            mountPath: /etc/certs
            readOnly: true
        env:
          - name: REGISTRY_HTTP_ADDR
            value: "0.0.0.0:443"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/etc/certs/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/etc/certs/tls.key"
      volumes:
        - name: certificate-volume
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
  namespace: conure-system
spec:
  selector:
    app: registry
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 443
    nodePort: 30050
---
