/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/coffeenights/conure/apis/core/v1alpha1"
	scheme "github.com/coffeenights/conure/pkg/client/core_conure/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkflowRunsGetter has a method to return a WorkflowRunInterface.
// A group's client should implement this interface.
type WorkflowRunsGetter interface {
	WorkflowRuns(namespace string) WorkflowRunInterface
}

// WorkflowRunInterface has methods to work with WorkflowRun resources.
type WorkflowRunInterface interface {
	Create(ctx context.Context, workflowRun *corev1alpha1.WorkflowRun, opts v1.CreateOptions) (*corev1alpha1.WorkflowRun, error)
	Update(ctx context.Context, workflowRun *corev1alpha1.WorkflowRun, opts v1.UpdateOptions) (*corev1alpha1.WorkflowRun, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workflowRun *corev1alpha1.WorkflowRun, opts v1.UpdateOptions) (*corev1alpha1.WorkflowRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.WorkflowRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.WorkflowRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.WorkflowRun, err error)
	WorkflowRunExpansion
}

// workflowRuns implements WorkflowRunInterface
type workflowRuns struct {
	*gentype.ClientWithList[*corev1alpha1.WorkflowRun, *corev1alpha1.WorkflowRunList]
}

// newWorkflowRuns returns a WorkflowRuns
func newWorkflowRuns(c *CoreV1alpha1Client, namespace string) *workflowRuns {
	return &workflowRuns{
		gentype.NewClientWithList[*corev1alpha1.WorkflowRun, *corev1alpha1.WorkflowRunList](
			"workflowruns",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.WorkflowRun { return &corev1alpha1.WorkflowRun{} },
			func() *corev1alpha1.WorkflowRunList { return &corev1alpha1.WorkflowRunList{} },
		),
	}
}
