apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: api-server
  labels:
    app: api-server
spec:
  type: ClusterIP
  selector:
    name: api-server
  ports:
  - name: http
    port: 80
    targetPort: 8080