apiVersion: core.conure.io/v1alpha1
kind: Workflow
metadata:
  name: webservice
  namespace: conure-system
spec:
  actions:
    - name: build-image
      values:
        gitRepository: "https://github.com/coffeenights/conure.git"
        branch: "main"
        imagePullSecretsName: "regcred"
        message: "Building Conure!"
        ociRepository: "registry-service.conure-system.svc.cluster.local:5000/conure/backend"
        ociTag: "latest"
        dockerFile: "cmd/api-server/Dockerfile"
        # storageSize: string