/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/coffeenights/conure/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkflowRuns implements WorkflowRunInterface
type FakeWorkflowRuns struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var workflowrunsResource = v1alpha1.SchemeGroupVersion.WithResource("workflowruns")

var workflowrunsKind = v1alpha1.SchemeGroupVersion.WithKind("WorkflowRun")

// Get takes name of the workflowRun, and returns the corresponding workflowRun object, and an error if there is any.
func (c *FakeWorkflowRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkflowRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workflowrunsResource, c.ns, name), &v1alpha1.WorkflowRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowRun), err
}

// List takes label and field selectors, and returns the list of WorkflowRuns that match those selectors.
func (c *FakeWorkflowRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkflowRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workflowrunsResource, workflowrunsKind, c.ns, opts), &v1alpha1.WorkflowRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkflowRunList{ListMeta: obj.(*v1alpha1.WorkflowRunList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkflowRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workflowRuns.
func (c *FakeWorkflowRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workflowrunsResource, c.ns, opts))

}

// Create takes the representation of a workflowRun and creates it.  Returns the server's representation of the workflowRun, and an error, if there is any.
func (c *FakeWorkflowRuns) Create(ctx context.Context, workflowRun *v1alpha1.WorkflowRun, opts v1.CreateOptions) (result *v1alpha1.WorkflowRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workflowrunsResource, c.ns, workflowRun), &v1alpha1.WorkflowRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowRun), err
}

// Update takes the representation of a workflowRun and updates it. Returns the server's representation of the workflowRun, and an error, if there is any.
func (c *FakeWorkflowRuns) Update(ctx context.Context, workflowRun *v1alpha1.WorkflowRun, opts v1.UpdateOptions) (result *v1alpha1.WorkflowRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workflowrunsResource, c.ns, workflowRun), &v1alpha1.WorkflowRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkflowRuns) UpdateStatus(ctx context.Context, workflowRun *v1alpha1.WorkflowRun, opts v1.UpdateOptions) (*v1alpha1.WorkflowRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workflowrunsResource, "status", c.ns, workflowRun), &v1alpha1.WorkflowRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowRun), err
}

// Delete takes name of the workflowRun and deletes it. Returns an error if one occurs.
func (c *FakeWorkflowRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(workflowrunsResource, c.ns, name, opts), &v1alpha1.WorkflowRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkflowRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workflowrunsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkflowRunList{})
	return err
}

// Patch applies the patch and returns the patched workflowRun.
func (c *FakeWorkflowRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkflowRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workflowrunsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkflowRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowRun), err
}
