/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/coffeenights/conure/apis/core/v1alpha1"
	corev1alpha1 "github.com/coffeenights/conure/pkg/client/core_conure/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActionDefinitions implements ActionDefinitionInterface
type fakeActionDefinitions struct {
	*gentype.FakeClientWithList[*v1alpha1.ActionDefinition, *v1alpha1.ActionDefinitionList]
	Fake *FakeCoreV1alpha1
}

func newFakeActionDefinitions(fake *FakeCoreV1alpha1, namespace string) corev1alpha1.ActionDefinitionInterface {
	return &fakeActionDefinitions{
		gentype.NewFakeClientWithList[*v1alpha1.ActionDefinition, *v1alpha1.ActionDefinitionList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("actiondefinitions"),
			v1alpha1.SchemeGroupVersion.WithKind("ActionDefinition"),
			func() *v1alpha1.ActionDefinition { return &v1alpha1.ActionDefinition{} },
			func() *v1alpha1.ActionDefinitionList { return &v1alpha1.ActionDefinitionList{} },
			func(dst, src *v1alpha1.ActionDefinitionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ActionDefinitionList) []*v1alpha1.ActionDefinition {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ActionDefinitionList, items []*v1alpha1.ActionDefinition) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
