{{- if .Values.apiServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conure.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "conure.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "conure.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "conure.api.selectorLabels" . | nindent 8 }}
        {{- with .Values.apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/api-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ printf "%s|%s" (.Values.apiServer.secrets.jwtSecret | default "") (include "conure.api.mongodbUri" .) | sha256sum }}
        {{- with .Values.apiServer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "conure.api.serviceAccountName" . }}
      {{- with .Values.apiServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api-server
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          {{- with .Values.apiServer.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "conure.api.configMapName" . }}
            - secretRef:
                name: {{ include "conure.api.secretName" . }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.apiServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
