version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./_data:/var/lib/postgresql/data/pgdata
      - /etc/passwd:/etc/passwd:ro
    environment:
      - POSTGRES_PASSWORD=test123
      - PGDATA=/var/lib/postgresql/_data/pgdata
      - POSTGRES_DB=conure_apps
      - POSTGRES_USER=conure_apps
