version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "54320:5432"
    volumes:
      - ./_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=test123
      - PGDATA=/var/lib/postgresql/_data/pgdata
      - POSTGRES_DB=conure_users
      - POSTGRES_USER=conure_users
